import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowDownToLine,ArrowRight,ArrowUpRight,BookHeart,BookOpen,CalendarDays,Check,ChevronRight,ClipboardCopy,CloudCheck,Download,ExternalLink,Gauge,Heart,House,Info,LayoutGrid,List,LoaderCircle,MapPin,MessageCircle,Plus,Printer,RefreshCw,Search,Settings2,ShieldCheck,Sparkles,Trash2,Users,Wallet,X} from 'lucide-react';
import {toast} from 'sonner';
import {Tabs,TabsContent,TabsList,TabsTrigger} from './components/ui/tabs';
import {Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle} from './components/ui/sheet';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from './components/ui/dialog';
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle} from './components/ui/alert-dialog';
import {Progress} from './components/ui/progress';
import {Input} from './components/ui/input';
import {Label} from './components/ui/label';
import {Toaster} from './components/ui/sonner';
import {Switch} from './components/ui/switch';
import {Action,Choice,downloadText,EmptyState,SaveAction,SectionTitle,SourceLink,StatusMark} from './components/book-controls';
import {MemoryForm,ProfileForm,TaskForm} from './components/notebook-forms';
import {chapters,emptyBook,inScope,type Book,type Memory,type Profile,type Task,type TaskRecord} from './lib/model';
import {calendarFile,deadlineText,difference,formatMoney,moneyTotals,monthDay,nearestDeadline,shortDate,taskDeadlines,todayJapan,type Deadline} from './lib/dates';
import {backupText,readBackup} from './lib/backup';
import {useBook} from './lib/use-book';
import {groups,reviewedOn,sources,taskById,tasks} from './data/catalog';
import {MarriageDesk} from './components/MarriageDesk';
const typeLabels={procedure:'手続き',benefit:'給付・助成',tax:'税の制度',investment:'資産形成',contract:'契約の見直し',conversation:'ふたりで話す'};
const nav=[{id:'desk',label:'デスク',icon:Gauge},{id:'journey',label:'ロードマップ',icon:House},{id:'deadlines',label:'期限と予定',icon:CalendarDays},{id:'memories',label:'記念手帳',icon:BookHeart},{id:'find',label:'制度を探す',icon:Search},{id:'settings',label:'ふたりの設定',icon:Settings2}];
type Modal='profile'|'pair'|'memory'|null;
export default function FutureNotebook(){
 const [tab,setTab]=useState('desk'),[chapter,setChapter]=useState('prepare'),[groupId,setGroupId]=useState(groups[0].id),[mapView,setMapView]=useState('board');
 const [taskId,setTaskId]=useState<string|null>(null),[modal,setModal]=useState<Modal>(null),[dirty,setDirty]=useState(false),[pendingClose,setPendingClose]=useState<(()=>void)|null>(null);
 const [query,setQuery]=useState(''),[category,setCategory]=useState('all'),[scopeOnly,setScopeOnly]=useState(false),[statusFilter,setStatusFilter]=useState('all');
 const [memoryDraft,setMemoryDraft]=useState<Memory|null>(null),[memoryFilter,setMemoryFilter]=useState('all'),[deleteMemory,setDeleteMemory]=useState<Memory|null>(null);
 const [joinCode,setJoinCode]=useState(''),[invite,setInvite]=useState<{code:string,expires:string,gift?:boolean}|null>(null),[importDraft,setImportDraft]=useState<{book:Book,legacy:boolean}|null>(null);
 const uploadRef=useRef<HTMLInputElement>(null);
 const data=useBook(!!modal||!!taskId||dirty),book=data.book||emptyBook,p=book.profile,today=todayJapan();
 const scoped=useMemo(()=>tasks.filter(t=>inScope(t,p)),[p]);
 const actionable=scoped.filter(t=>book.records[t.id]?.status!=='na'),done=actionable.filter(t=>book.records[t.id]?.status==='done');
 const activeChapter=chapters.find(c=>c.id===chapter)!;
 const chapterGroups=groups.filter(g=>g.chapter===chapter);
 const activeGroup=chapterGroups.find(g=>g.id===groupId)||chapterGroups[0];
 const currentTasks=activeGroup?scoped.filter(t=>activeGroup.ids.includes(t.id)):[];
 const task=taskId?taskById[taskId]:null;
 const dates=useMemo(()=>scoped.filter(t=>!['done','na'].includes(book.records[t.id]?.status||'todo')).flatMap(task=>taskDeadlines(task,p,book.records[task.id]).map(deadline=>({task,deadline}))).sort((a,b)=>(a.deadline.date||'9999').localeCompare(b.deadline.date||'9999')),[scoped,p,book.records]);
 const dated=dates.filter(x=>x.deadline.date),missingDates=dates.filter(x=>!x.deadline.date),soon=dated.filter(x=>difference(x.deadline.date,today)<=14);
 const next=actionable.filter(t=>!['done','applied','waiting'].includes(book.records[t.id]?.status||'todo')).sort((a,b)=>{
  const da=nearestDeadline(a,p,book.records[a.id])?.date||'9999',db=nearestDeadline(b,p,book.records[b.id])?.date||'9999';
  if(da!==db)return da.localeCompare(db);const priority=['A無1','A必1','P1','A必3','C14-1'];const ai=priority.indexOf(a.id),bi=priority.indexOf(b.id);return (ai<0?999:ai)-(bi<0?999:bi);
 }).slice(0,3);
 const filtered=tasks.filter(t=>(!scopeOnly||inScope(t,p))&&(category==='all'||t.chapter===category)&&(statusFilter==='all'||(book.records[t.id]?.status||'todo')===statusFilter)&&(!query||`${t.title} ${t.summary} ${t.sources.map(s=>sources[s].title).join(' ')}`.normalize('NFKC').toLowerCase().includes(query.normalize('NFKC').toLowerCase().trim())));
 const totals=moneyTotals(book),memoryRows=book.memories.filter(m=>memoryFilter==='all'||m.kind===memoryFilter).sort((a,b)=>(b.date||'').localeCompare(a.date||''));
 const firstSteps=tasks.filter(t=>['prepare','life'].includes(t.chapter)&&inScope(t,p)&&book.records[t.id]?.status!=='na');
 const newLifeReady=firstSteps.length>0&&firstSteps.every(t=>book.records[t.id]?.status==='done');
 const callClose=(action:()=>void)=>{if(data.busy)return;if(dirty)setPendingClose(()=>action);else{setDirty(false);action();}};
 const forceClose=()=>{setDirty(false);setTaskId(null);setModal(null);};
 const openTask=(id:string)=>{setDirty(false);setTaskId(id);};
 const openProfile=()=>{callClose(()=>{setTaskId(null);setDirty(false);setModal('profile');});};
 const selectChapter=(id:string)=>{setChapter(id);setGroupId(groups.find(g=>g.chapter===id)?.id||'');};
 const newMemory=(kind:Memory['kind']='memory')=>{setMemoryDraft({id:crypto.randomUUID(),date:today,title:kind==='monthly'?`${Number(today.slice(5,7))}月のふたり会議`:'',text:kind==='monthly'?'今月うれしかったこと：\n\nありがとうを伝えたいこと：\n\n来月の楽しみ：\n\n見直したい予定・お金のこと：\n':'',kind,complete:false});setModal('memory');setDirty(false);};
 const saveRecord=async(r:TaskRecord)=>{if(!task)return;const result=await data.mutate({action:'record',id:task.id,record:r},r.status==='done'?'記録を保存しました':'ふたりの記録を保存しました');if(result)forceClose();};
 const saveProfile=async(profile:Profile)=>{if(await data.mutate({action:'profile',profile},'ふたりに合わせて手帳を整えました'))forceClose();};
 const saveMemory=async(memory:Memory)=>{if(await data.mutate({action:'memory',memory},'ふたりの言葉を残しました'))forceClose();};
 const copy=async(text:string)=>{try{await navigator.clipboard.writeText(text);toast.success('コピーしました');}catch{toast.error('コピーできませんでした。コードを選択してコピーしてください。');}};
 const exportBackup=()=>{if(!data.book){toast.info('手帳を始めてから保存できます');return;}downloadText(`futari-miraicho-${today}.json`,backupText(data.book));toast.success('バックアップを書き出しました');};
 const exportCalendar=()=>{if(!dated.length){toast.info('基準の日付か予定日を設定してください');return;}downloadText('futari-calendar.ics',calendarFile(dated),'text/calendar;charset=utf-8');toast.success('予定を書き出しました。お使いのカレンダーに読み込んでください。');};
 const loadBackup=async(file:File)=>{try{if(file.size>2000000)throw new Error('2MB以内のJSONファイルを選んでください。');setImportDraft(readBackup(JSON.parse(await file.text())));}catch(e){toast.error(e instanceof Error?e.message:'読み込めませんでした');}};
 useEffect(()=>{if(!dirty)return;const before=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before);},[dirty]);
 const renderTask=(t:Task,compact=false)=>{const r=book.records[t.id],deadline=nearestDeadline(t,p,r);return <button key={t.id} className={`task-row ${compact?'compact':''} ${r?.status==='done'?'task-done':''}`} onClick={()=>openTask(t.id)}><span className="task-circle">{r?.status==='done'?<Check size={17}/>:t.type==='conversation'?<Heart size={16}/>:<span/>}</span><span className="task-row-body"><span className="task-row-top"><span className="task-type">{typeLabels[t.type]}</span>{r&&<StatusMark status={r.status}/>}</span><strong>{t.title}</strong>{!compact&&<span className="task-summary">{t.summary}</span>}<span className="task-meta">{deadline&&!['done','na'].includes(r?.status||'')&&<span className={difference(deadline.date,today)<=7?'urgency':''}><CalendarDays size={13}/>{monthDay(deadline.date)} · {deadline.kind==='personal'?'予定':deadline.uncertain?'原則日':'届出期限'}</span>}{r?.assignee&&<span><Users size={13}/>{r.assignee==='together'?'二人で':r.assignee==='one'?p.name1||'一人目':p.name2||'二人目'}</span>}</span></span><ChevronRight size={17}/></button>;};
 return <><a className="skip-link" href="#main-content">本文へ進む</a><Toaster theme="light" position="top-center" richColors/>
 <header className="masthead"><div className="masthead-inner"><button className="brand" onClick={()=>setTab('desk')} aria-label="ふたりの未来帖 ホーム"><span className="brand-seal">結</span><span className="wordmark">ふたりの未来帖<small>FUTARI NO MIRAICHO</small></span></button><div className="header-right"><span className="city-tag"><MapPin size={15}/>広島市{p.ward!=='未設定'?` ${p.ward}`:''}</span><button className="pair-pill" onClick={()=>{setInvite(null);setModal('pair');}}><Users size={16}/><span>{data.members.length===2?'二人の手帳':'ふたりで使う'}</span></button></div></div></header>
 <Tabs value={tab} onValueChange={setTab} className="notebook-tabs"><div className="nav-wrap"><TabsList className="main-nav" aria-label="メインメニュー">{nav.map(n=><TabsTrigger key={n.id} value={n.id}><n.icon/><span>{n.label}</span>{n.id==='deadlines'&&soon.length>0&&<i className="nav-dot"/>}</TabsTrigger>)}</TabsList><span className="save-status" role="status">{data.busy?<><LoaderCircle className="spin" size={14}/>保存中</>:data.phase==='loading'?<>読み込み中…</>:data.phase==='error'?<>接続を確認</>:data.book?<><CloudCheck size={15}/>この端末に保存済み</>:<>まだ手帳を始めていません</>}</span></div>
 <main className="workspace" id="main-content">
 {data.error&&<div className="connection-error" role="alert"><Info size={18}/><p>{data.error}</p>{data.phase==='signin'?<a href="/signin-with-chatgpt?return_to=%2F" target="_top">ログインする</a>:<button onClick={()=>void data.refresh()}>再読み込み</button>}</div>}
 <TabsContent value="desk" className="tab-surface">
 <MarriageDesk book={book} profile={p} scoped={scoped} actionable={actionable} done={done} soonCount={soon.length} today={today} hasBook={!!data.book} onOpenTask={openTask} onOpenProfile={openProfile} onGoJourney={()=>setTab('journey')}/>
 </TabsContent>
 <TabsContent value="journey" className="tab-surface">
 <div className="welcome-line"><div><p className="eyebrow">A LITTLE STEP, A LOVELY FUTURE</p><h1>{p.name1&&p.name2?`${p.name1}さんと${p.name2}さんの、これから。`:'ふたりの未来に、小さな一歩を。'}</h1><p className="muted">必要な手続きと制度を、二人のペースで確かめる手帳。</p></div><button className="quiet-button" onClick={openProfile}><Settings2 size={16}/>ふたりに合わせる</button></div>
 <div className="home-top"><section className="today-panel"><div className="panel-label"><span><span className="gold-dot"/>今日のひとつ、ここから。</span><small>{today.replace(/-/g,'.')}</small></div>
 {!data.book&&data.phase==='ready'&&<div className="start-note"><div><strong>二人だけの手帳をはじめよう</strong><p>呼び名や予定を入れると、今の二人に合わせて表示できます。</p></div><Action onClick={openProfile}>手帳を整える<ArrowRight/></Action></div>}
 <div className="next-actions">{next.length?next.map((t,i)=><button className="next-action" key={t.id} onClick={()=>openTask(t.id)}><span className="next-num">0{i+1}</span><span><small>{nearestDeadline(t,p,book.records[t.id])?'期限・予定を確認':typeLabels[t.type]}</small><strong>{t.title}</strong></span><ArrowUpRight size={19}/></button>):<div className="small-empty"><Sparkles size={20}/><p>今の候補はひと通り確認できました。結果待ちや、次の楽しみを手帳で確かめましょう。</p></div>}</div>
 <div className="progress-strip"><div><span>これまでの一歩</span><strong>{done.length}<small> / {actionable.length} 項目</small></strong></div><Progress value={actionable.length?done.length/actionable.length*100:0} aria-label="対象項目の完了率"/><span className="stamp-mini">歩</span></div></section>
 <aside className="paper-card tip-card"><span className="eyebrow">CHECK FIRST</span><h3>公式案内で確かめる</h3><p>表示は候補です。金額や対象条件は、各項目の公式参照先と窓口で確認してください。</p><p className="hint">{p.wdate?`婚姻日：${shortDate(p.wdate)}`:'婚姻日は設定から入れられます。'}</p><button className="text-button" onClick={openProfile}>ふたりの設定を開く<ArrowRight size={14}/></button></aside></div>
 <div className="section-heading"><div><p className="eyebrow">OUR JOURNEY</p><h2>ふたりの、暮らしロードマップ</h2></div><div className="view-switch" role="group" aria-label="表示方法"><button className={mapView==='board'?'active':''} onClick={()=>setMapView('board')} aria-label="ロードマップで見る"><LayoutGrid size={16}/></button><button className={mapView==='list'?'active':''} onClick={()=>setMapView('list')} aria-label="一覧で見る"><List size={17}/></button></div></div>
 <div className="chapter-nav" role="group" aria-label="暮らしの章">{chapters.map(c=>{const count=scoped.filter(t=>t.chapter===c.id&&book.records[t.id]?.status!=='na');const n=count.filter(t=>book.records[t.id]?.status==='done').length;return <button key={c.id} className={chapter===c.id?'active':''} onClick={()=>selectChapter(c.id)} aria-pressed={chapter===c.id}><span className="chapter-kanji">{c.kanji}</span><span>{c.label}<small>{count.length?`${n} / ${count.length}`:'必要になったら'}</small></span>{count.length>0&&n===count.length&&<Check size={15}/>}</button>;})}</div>
 <section className="journey-panel"><div className="journey-heading"><div><span className="eyebrow">{activeChapter.en}</span><h3>{activeChapter.description}</h3></div><span className="hint">順番は自由。必要なマスからどうぞ。</span></div>
 {chapter==='child'&&['unknown','none'].includes(p.child)?<EmptyState symbol={<Heart/>} title="必要になった時に、この章を。" action={<Action secondary onClick={openProfile}>表示する段階を選ぶ</Action>}>妊娠・出産・子育ての項目は、今の二人の希望に合わせて開けます。</EmptyState>:<>
 {mapView==='board'?<div className="sugoroku-board">{chapterGroups.map((g,i)=>{const ts=scoped.filter(t=>g.ids.includes(t.id)&&book.records[t.id]?.status!=='na'),n=ts.filter(t=>book.records[t.id]?.status==='done').length,complete=ts.length>0&&n===ts.length;return <button key={g.id} onClick={()=>setGroupId(g.id)} className={`square ${activeGroup?.id===g.id?'selected':''} ${complete?'complete':''}`} aria-pressed={activeGroup?.id===g.id}><span className="square-no">{String(i+1).padStart(2,'0')}</span><span className="square-seal">{complete?'済':g.kanji}</span><strong>{g.short}</strong><span>{ts.length?`${n} / ${ts.length} 完了`:'対象項目なし'}</span><i className="square-line"/></button>;})}</div>:<div className="chapter-list">{scoped.filter(t=>t.chapter===chapter).map(t=>renderTask(t,true))}</div>}
 {mapView==='board'&&activeGroup&&<div className="square-detail"><div className="square-detail-head"><h3><span>{activeGroup.kanji}</span>{activeGroup.title}</h3><small>{currentTasks.length}項目</small></div>{currentTasks.length?currentTasks.map(t=>renderTask(t)):<div className="small-empty">現在の設定に当てはまる項目はありません。設定や「制度を探す」から確認できます。</div>}</div>}
 </>}
 </section>
 <div className={`milestone ${newLifeReady?'reached':''}`}><span className="milestone-seal">進</span><div><h3>{newLifeReady?'結婚準備と新生活の項目をひと通り確認しました。':'一歩ずつ、ふたりの暮らしに。'}</h3><p>{newLifeReady?'必要ならメモや次の予定を、記念手帳に残せます。':'結婚準備と新生活の項目を進めると、ここに進捗がまとまります。'}</p></div>{newLifeReady&&<Action secondary onClick={()=>newMemory()}>メモを残す</Action>}</div>
 <div className="home-bottom"><button className="monthly-invite" onClick={()=>newMemory('monthly')}><MessageCircle/><span><small>月に一度、10分だけ。</small><strong>お茶を飲みながら、ふたり会議。</strong><span>ありがとうと、来月の楽しみを。</span></span><ArrowRight/></button><div className="local-note"><MapPin size={19}/><div><strong>広島市の制度から、確かめる。</strong><p>結婚新生活支援事業は市では未実施と案内されています。勤務先や他の支援はそれぞれ確認できます。</p><a href={sources.nogrant.url} target="_blank" rel="noreferrer">市の案内 · {reviewedOn}確認<ExternalLink size={12}/></a></div></div></div>
 </TabsContent>
 <TabsContent value="deadlines" className="tab-surface"><SectionTitle eyebrow="TIME FOR THE TWO OF US" title="期限と、ふたりの予定。" sub="済んだ手続きは外して、これからの予定を日付順に。"><Action secondary onClick={exportCalendar} disabled={!dated.length}><Download/>カレンダーに書き出す</Action></SectionTitle>
 <div className="schedule-layout"><section><div className="schedule-summary"><div><strong>{dated.length}</strong><span>日付のある予定</span></div><div><strong>{soon.length}</strong><span>14日以内・経過した原則日</span></div><button onClick={openProfile}><Settings2 size={17}/>基準の日付を整える</button></div>
 {dated.length?<div className="timeline">{dated.map(({task:t,deadline:d},i)=><button className={`timeline-item ${difference(d.date,today)<=7?'near':''}`} key={`${t.id}-${d.kind}`} onClick={()=>openTask(t.id)}><span className="timeline-date"><small>{d.date.slice(0,4)}年</small><strong>{monthDay(d.date)}</strong><span>{new Intl.DateTimeFormat('ja-JP',{weekday:'short',timeZone:'UTC'}).format(new Date(d.date+'T00:00:00Z'))}曜日</span></span><span className="timeline-body"><span className="timeline-top"><span className={`status ${d.kind==='personal'?'status-learned':''}`}>{d.kind==='personal'?'二人の予定':d.uncertain?'原則日・要確認':'届出期限'}</span><span className="countdown">{deadlineText(d.date,today)}</span></span><strong>{t.title}</strong><span>{d.basis}</span></span><ChevronRight size={18}/></button>)}</div>:<EmptyState symbol={<CalendarDays/>} title="次の予定を、ひとつ決めよう。" action={<Action secondary onClick={openProfile}>基準の日付を設定する</Action>}>日付が分かれば期限を確認できます。各項目に、二人で決めた予定日を入れることもできます。</EmptyState>}
 {missingDates.length>0&&<section className="missing-dates"><h3>日付が分かったら確認すること <span>{missingDates.length}</span></h3>{missingDates.map(({task:t,deadline:d})=><button key={t.id} onClick={()=>openTask(t.id)}><span><strong>{t.title}</strong><small>{d.missing}が未設定</small></span><ChevronRight size={16}/></button>)}</section>}
 </section><aside className="schedule-aside"><div className="paper-card"><span className="eyebrow">BEFORE YOU GO</span><h3>窓口へ行く、その前に。</h3><p>表示した日付は原則の計算です。対象条件や受付方法も、各手続きの公式案内で確認してください。</p><p>出生届の休日補正は、確認できた2026・2027年の祝日を使っています。それ以外の年や他の手続きの休日は、窓口への確認を表示します。</p><SourceLink source={sources.holidays} compact/></div><div className="paper-card"><CalendarDays size={23}/><h3>いつものカレンダーへ。</h3><p>書き出したファイルをGoogle・Appleなどのカレンダーへ読み込めます。3日前の通知を含みますが、通知されるかはカレンダー側の設定によります。</p><p className="hint">この手帳自体から通知は届きません。予定を変えた場合は、取り込んだ予定も更新してください。</p></div></aside></div></TabsContent>
 <TabsContent value="memories" className="tab-surface"><SectionTitle eyebrow="THE DAYS WE WANT TO REMEMBER" title="ふたりの記念手帳。" sub="手続きの先にある、日々のうれしいことを。"><Action onClick={()=>newMemory()}><Plus/>記念を残す</Action></SectionTitle>
 <section className="memory-hero"><div><span className="eyebrow">ONE DAY, AND EVERY DAY</span><h2>{p.wdate?difference(today,p.wdate)>=0?`婚姻日から、${difference(today,p.wdate)+1}日目。`:`婚姻日まで、あと${difference(p.wdate,today)}日。`:'日付を入れると、日数が表示されます。'}</h2><p>{book.memories.length?`${book.memories.length}件の言葉と、${done.length}個の「できた」が重なりました。`:'最初のページには、今の気持ちを書いてみませんか。'}</p></div><span className="memory-hero-mark">記</span></section>
 <div className="money-section"><div className="section-heading"><h2>暮らしに増えた、ゆとり。</h2><span className="hint">各項目で二人が入力した金額を集計</span></div><div className="money-grid">{([{key:'received',label:'受け取った給付・祝金',unit:'円',sub:'受取を記録した金額'},{key:'estimate',label:'これからの受取見込み',unit:'円',sub:'未受取・給付の確約ではありません'},{key:'monthlySaving',label:'固定費の削減',unit:'円／月',sub:'二人が確認した月額の差'},{key:'taxEstimate',label:'税負担の軽減見込み',unit:'円',sub:'控除対象額とは異なります'}] as const).map(m=><div className={`money-card ${m.key==='received'?'primary':''}`} key={m.key}><span>{m.label}</span><strong>{Object.values(book.records).some(r=>r.moneyKind===m.key&&r.amount!==null&&r.status!=='na')?formatMoney(totals[m.key]):'—'}<small>{m.unit}</small></strong><p>{m.sub}</p></div>)}</div><p className="hint">投資枠・運用益は集計しません。異なる期間や区分の金額を足した「総お得額」は表示していません。同じ給付を重複して入力していないか、記録を確認してください。</p></div>
 <div className="memory-toolbar"><div className="filter-pills" role="group" aria-label="記録の種類">{Object.entries({all:'すべて',memory:'思い出',monthly:'ふたり会議',dream:'叶えたいこと'}).map(([v,label])=><button key={v} className={memoryFilter===v?'active':''} onClick={()=>setMemoryFilter(v)} aria-pressed={memoryFilter===v}>{label}</button>)}</div><button className="text-button" onClick={()=>newMemory('dream')}><Plus size={16}/>やりたいことを追加</button></div>
 {memoryRows.length?<div className="memory-grid">{memoryRows.map(m=><article key={m.id} className={`memory-card kind-${m.kind}`}><div className="memory-card-top"><span>{m.kind==='monthly'?'ふたり会議':m.kind==='dream'?'これから叶えたいこと':'ふたりの思い出'}</span>{m.kind==='dream'?<Sparkles size={19}/>:<Heart size={18}/>}</div><small>{m.date?shortDate(m.date):'日付はこれから'}</small><h3>{m.title}</h3>{m.complete&&m.kind==='dream'&&<span className="dream-complete"><Check size={14}/>二人で叶えました</span>}<p>{m.text||'言葉は、またあとで。'}</p><div className="memory-card-actions"><button className="text-button" onClick={()=>{setMemoryDraft(m);setDirty(false);setModal('memory');}}>続きを書く<ArrowRight size={14}/></button><button className="icon-button" aria-label={`${m.title}を削除する`} onClick={()=>setDeleteMemory(m)}><Trash2 size={15}/></button></div></article>)}</div>:<EmptyState symbol={<BookHeart/>} title="今日を、最初のページに。" action={<Action secondary onClick={()=>newMemory('monthly')}><MessageCircle/>ふたり会議を書いてみる</Action>}>「ありがとう」「来月楽しみなこと」。短い言葉だけでも、二人の記念になります。</EmptyState>}
 </TabsContent>
 <TabsContent value="find" className="tab-surface"><SectionTitle eyebrow="A GUIDE TO EVERYDAY LIFE" title="二人に必要な制度を探す。" sub="手続き、税、勤務先の制度、暮らしの工夫。149項目を収録しています。"/>
 <div className="search-panel"><label className="search-box"><Search size={21}/><Input aria-label="制度を検索" value={query} onChange={e=>setQuery(e.target.value)} placeholder="例：結婚祝金、引っ越し、NISA、育休…"/>{query&&<button className="icon-button" onClick={()=>setQuery('')} aria-label="検索をクリア"><X size={17}/></button>}</label><div className="search-filters"><Choice label="暮らしの章" value={category} onChange={setCategory} options={{all:'すべての章',...Object.fromEntries(chapters.map(c=>[c.id,c.label]))}}/><Choice label="記録の状況" value={statusFilter} onChange={setStatusFilter} options={{all:'すべての状況',todo:'これから',learned:'確認した',preparing:'準備中',applied:'申請した',waiting:'結果待ち',done:'完了',na:'今回は対象外'}}/><label className="scope-toggle"><Switch checked={scopeOnly} onCheckedChange={setScopeOnly}/><span>現在の二人の候補だけ</span></label></div></div>
 <div className="results-label"><strong>{filtered.length}件</strong><span>表示は対象の確定ではありません。個別の条件を確認してください。</span></div>
 {filtered.length?<section className="results-list">{filtered.map(t=>renderTask(t))}</section>:<EmptyState symbol={<Search/>} title="当てはまる項目がありません。" action={<Action secondary onClick={()=>{setQuery('');setCategory('all');setStatusFilter('all');setScopeOnly(false);}}>条件をリセットする</Action>}>短い言葉で探すか、章や状況の条件を変えてみてください。</EmptyState>}
 </TabsContent>
 <TabsContent value="settings" className="tab-surface"><SectionTitle eyebrow="MAKE THIS NOTEBOOK YOURS" title="ふたりらしい手帳に。" sub="呼び名、共有、バックアップ。いつでも整え直せます。"/>
 <div className="settings-grid"><section className="paper-card settings-card"><div className="settings-icon"><Users/></div><h2>ふたりのプロフィール</h2><p className="profile-names">{p.name1||'一人目'} <span>&</span> {p.name2||'二人目'}</p><dl><div><dt>住まい</dt><dd>広島市 {p.ward==='未設定'?'（区は未設定）':p.ward}</dd></div><div><dt>婚姻日・予定日</dt><dd>{p.wdate?shortDate(p.wdate):'未設定'}</dd></div><div><dt>子育ての章</dt><dd>{['unknown','none'].includes(p.child)?'表示していません':'選んだ段階を表示'}</dd></div></dl><Action secondary onClick={openProfile}>プロフィールを整える<ArrowRight/></Action></section>
 <section className="paper-card settings-card"><div className="settings-icon"><Heart/></div><h2>同じ手帳を、二人で。</h2><p>この公開版はブラウザの端末内に保存します。招待コードやクラウド共有は未対応です。バックアップの書き出し／読み込みで受け渡せます。</p><div className="member-list">{data.members.length?data.members.map(m=><div key={m.slot}><span>{m.slot===1?'一':'二'}</span><p>{m.display_name}<small>{m.slot===data.slot?'あなた':'同じ手帳のメンバー'}</small></p><Check size={15}/></div>):<p className="hint">まだ手帳を作成・受け取りしていません。</p>}</div><Action secondary onClick={()=>{setInvite(null);setModal('pair');}}><Users/>共有・手帳を受け取る</Action></section>
 <section className="paper-card settings-card"><div className="settings-icon"><ShieldCheck/></div><h2>この端末に保存します。</h2><p>進捗・メモ・金額はブラウザ内に残ります。端末を変えるときはバックアップJSONを書き出してください。</p><p className="hint">二人で使う場合は、バックアップの受け渡しか「ふたりで使う」から始めてください。</p><div className="stack-actions"><Action secondary onClick={exportBackup}><Download/>バックアップを書き出す</Action></div></section>
 <section className="paper-card settings-card"><div className="settings-icon"><ArrowDownToLine/></div><h2>大切な記録を手元にも。</h2><p>バックアップには、名前・日付・メモを含みます。保管先と渡す相手を選んでください。</p><input ref={uploadRef} type="file" accept=".json,application/json" className="sr-only" aria-label="手帳のバックアップ" onChange={e=>{const file=e.target.files?.[0];if(file)void loadBackup(file);e.target.value='';}}/><div className="stack-actions"><Action secondary onClick={exportBackup} disabled={!data.book}><Download/>バックアップを書き出す</Action><Action secondary onClick={()=>uploadRef.current?.click()}><ArrowUpRight/>バックアップ・旧版を読み込む</Action><Action secondary onClick={()=>window.print()}><Printer/>手帳を印刷・PDFにする</Action></div><p className="hint">旧版は書き出したJSONに対応しています。データはこの端末に自動移行されません。</p></section></div>
 <section className="source-policy paper-card"><div><ShieldCheck size={25}/><h2>安心して確かめるために。</h2><p>この手帳は、制度を調べて手続きを進めるための案内です。給付や税の適用は、二人の条件と申請先の判断で決まります。</p><p>内容を確認した日を参照先ごとに表示しています。未確認の案内はその旨を表示し、勤務先・契約ごとの条件は窓口への質問としてまとめています。</p><p>制度の更新は自動配信されません。申請・契約の前には、公式案内と予算・受付状況を再確認してください。</p></div><div><h3>使い続けるためのメモ</h3><ul><li>記録はこの端末のブラウザに保存されます（localStorage）。</li><li>別の端末と同期したい場合は、バックアップJSONを書き出して読み込んでください。</li><li>招待コード・アカウント共有・クラウド同期はこの公開版では使えません。</li><li>スマートフォンのブラウザーの「ホーム画面に追加」から、すぐ開けるようにできます。</li></ul><button className="text-button" onClick={()=>void data.refresh()}><RefreshCw size={15}/>最新の保存内容を読み込む</button></div></section>
 </TabsContent>
 <footer className="book-footer"><span>ふたりの未来帖 <i> · </i> 広島市</span><p>急がなくて大丈夫。ふたりのペースで。</p><span>案内の確認日 {reviewedOn}</span></footer>
 </main></Tabs>
 <Sheet open={!!task} onOpenChange={open=>{if(!open)callClose(forceClose);}}><SheetContent side="right" className="task-sheet"><SheetHeader><span className="eyebrow">{task?typeLabels[task.type]:''} <i> / </i> ふたりの一歩</span><SheetTitle>{task?.title}</SheetTitle><SheetDescription>{task?.summary}</SheetDescription></SheetHeader>{task&&<TaskForm key={task.id} task={task} profile={p} record={book.records[task.id]} onSave={saveRecord} busy={data.busy} onDirty={setDirty} hasBook={!!data.book} onProfile={openProfile}/>}</SheetContent></Sheet>
 <Dialog open={!!modal} onOpenChange={open=>{if(!open)callClose(forceClose);}}><DialogContent className={`notebook-dialog dialog-${modal}`}><DialogHeader><p className="eyebrow">OUR NOTEBOOK</p><DialogTitle>{modal==='profile'?'ふたりに合わせて、整える。':modal==='pair'?'同じ手帳を、ひらこう。':'今日の気持ちを、ひとこと。'}</DialogTitle><DialogDescription>{modal==='profile'?'すべての項目はあとから変えられます。':modal==='pair'?'この公開版は端末内の保存です。バックアップJSONで受け渡せます。':'短い言葉からでも、大丈夫です。'}</DialogDescription></DialogHeader>
 {modal==='profile'&&<ProfileForm profile={p} onSave={saveProfile} busy={data.busy} onDirty={setDirty} hasBook={!!data.book}/>}
 {modal==='memory'&&memoryDraft&&<MemoryForm key={memoryDraft.id} initial={memoryDraft} onSave={saveMemory} busy={data.busy} onDirty={setDirty}/>}
 {modal==='pair'&&<div className="form-stack pair-content">{!data.book?<><div className="condition-note"><Users size={19}/><p>パートナーからコードを受け取った場合は、最初にここで入力してください。</p></div><div className="field"><Label htmlFor="join-code">受け取り・招待コード</Label><Input id="join-code" value={joinCode} onChange={e=>setJoinCode(e.target.value)} placeholder="受け取ったコードを貼り付ける" maxLength={100} autoComplete="off"/></div><SaveAction busy={data.busy} disabled={!/^[a-f0-9]{48}$/.test(joinCode.trim().toLowerCase())} onClick={()=>void(async()=>{if(await data.mutate({action:'join',code:joinCode.trim().toLowerCase()},'同じ手帳につながりました')){setJoinCode('');forceClose();}})()}>手帳を受け取る</SaveAction><div className="pair-divider">自分たちで始める場合</div><Action secondary onClick={()=>setModal('profile')}>新しい手帳を整える<ArrowRight/></Action></>:<><div className="member-list">{data.members.map(m=><div key={m.slot}><span>{m.slot===1?'一':'二'}</span><p>{m.display_name}<small>{m.slot===data.slot?'あなた':'同じ手帳のメンバー'}</small></p><Check size={16}/></div>)}</div>{data.members.length===2?<div className="condition-note"><Heart size={20}/><p>二人とも参加しています。それぞれの端末で、このページを開いて使えます。</p></div>:data.slot===1?<><p>招待コードを相手に渡すと、同じ手帳を使えます。コードは7日間有効で、一度だけ使えます。</p>{invite&&!invite.gift?<div className="invite-result"><Label>二人目の招待コード</Label><code>{invite.code}</code><span>有効期限 {new Date(invite.expires).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})}（日本時間）</span><Action secondary onClick={()=>void copy(invite.code)}><ClipboardCopy/>コードをコピー</Action><button className="text-button" disabled={data.busy} onClick={()=>void(async()=>{if(await data.mutate({action:'revokeInvite'},'招待を無効にしました'))setInvite(null);})()}>この招待を無効にする</button></div>:<SaveAction busy={data.busy} onClick={()=>void(async()=>{await data.mutate({action:'invite'},'');})()}>二人目を招待するコードを作る</SaveAction>}</>:<p>招待コードは、この手帳を作成した方が発行できます。</p>}<p className="hint">現在のアカウントはこの手帳に参加済みです。別の手帳のコードは、まだ手帳を受け取っていない相手のアカウントで入力してください。</p></>}
 <div className="notice-box"><strong>相手がこのページを開けることも必要です</strong><p>コードは手帳を共有するためのものです。ページ自体が開けない場合は、贈る方にサイトの共有設定を依頼してください。コードだけではページの閲覧権限は増えません。</p></div></div>}
 </DialogContent></Dialog>
 <AlertDialog open={!!pendingClose} onOpenChange={open=>{if(!open)setPendingClose(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>入力中の内容を閉じますか？</AlertDialogTitle><AlertDialogDescription>まだ保存していない変更があります。編集を続けるか、変更を破棄して閉じられます。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>編集を続ける</AlertDialogCancel><AlertDialogAction onClick={()=>{setDirty(false);pendingClose?.();setPendingClose(null);}}>変更を破棄して閉じる</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={!!deleteMemory} onOpenChange={open=>{if(!open&&!data.busy)setDeleteMemory(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>この記録を削除しますか？</AlertDialogTitle><AlertDialogDescription>「{deleteMemory?.title}」を二人の手帳から削除します。必要なら先にバックアップを保存してください。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={data.busy}>残しておく</AlertDialogCancel><AlertDialogAction disabled={data.busy} onClick={e=>{e.preventDefault();void(async()=>{if(deleteMemory&&await data.mutate({action:'deleteMemory',id:deleteMemory.id},'記録を削除しました'))setDeleteMemory(null);})();}}>削除する</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={!!importDraft} onOpenChange={open=>{if(!open&&!data.busy)setImportDraft(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>このバックアップを読み込みますか？</AlertDialogTitle><AlertDialogDescription>{importDraft?.legacy?'旧版の状況を移行します。手順が変わっているため、旧版の小さなチェックと調査メモ・除外理由は自動移行しません。働き方は各自で設定し直してください。':'名前・日付・進捗・記念手帳を復元します。'} 現在の二人の手帳の内容は、このバックアップで置き換わります。</AlertDialogDescription></AlertDialogHeader><div className="import-details"><p>{importDraft?.book.profile.name1||'名前未設定'} & {importDraft?.book.profile.name2||'名前未設定'}</p><p>{Object.keys(importDraft?.book.records||{}).length}項目の記録 · {importDraft?.book.memories.length}件の記念</p><Action secondary onClick={exportBackup} disabled={!data.book}><Download/>現在の内容を先に書き出す</Action></div><AlertDialogFooter><AlertDialogCancel disabled={data.busy}>キャンセル</AlertDialogCancel><AlertDialogAction disabled={data.busy} onClick={e=>{e.preventDefault();void(async()=>{if(importDraft&&await data.mutate({action:'import',book:importDraft.book},'手帳を読み込みました'))setImportDraft(null);})();}}>この内容に置き換える</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>

 <div className="print-book"><h1>ふたりの未来帖</h1><h2>{p.name1||'一人目'}さん & {p.name2||'二人目'}さん</h2><p>広島市 {p.ward!=='未設定'?p.ward:''} · 書き出し {shortDate(today)}</p><h2>これまでの一歩</h2><p>{done.length}項目が完了</p><table><thead><tr><th>項目</th><th>状況・記録</th></tr></thead><tbody>{tasks.filter(t=>book.records[t.id]).map(t=><tr key={t.id}><td>{t.title}</td><td>{book.records[t.id].status} · {book.records[t.id].note}<br/>{book.records[t.id].due&&`予定：${book.records[t.id].due}`}</td></tr>)}</tbody></table><h2>これからの予定</h2>{dated.map(({task:t,deadline:d})=><p key={`${t.id}-${d.kind}`}>{d.date} · {t.title} · {d.kind==='personal'?'二人の予定':'原則・条件を確認'}<br/>{d.basis}</p>)}<h2>ふたりの言葉</h2>{book.memories.map(m=><section key={m.id}><h3>{m.date} {m.title}</h3><p className="print-letter">{m.text}</p></section>)}<p>各制度の最新条件は手帳内の公式参照先で確認してください。案内の内容確認日：{reviewedOn}</p></div>
 </>;
}
